#!/usr/bin/env python3
"""Check whether Y=3/8 lies on ordinary SM/SU(5) charge lattices."""

from __future__ import annotations

import sympy as sp


def su2_component_charges(isospin: sp.Rational, hypercharge: sp.Rational) -> list[sp.Rational]:
    two_j = int(2 * isospin)
    ms = [sp.Rational(-two_j + 2 * k, 2) for k in range(two_j + 1)]
    return [sp.simplify(m + hypercharge) for m in ms]


def main() -> None:
    q = sp.Rational(3, 8)
    sm_unit = sp.Rational(1, 6)
    color_singlet_integer_unit = sp.Rational(1, 1)
    quark_electric_unit = sp.Rational(1, 3)

    print("Charge lattice check for Y=3/8")
    print("--------------------------------")
    print(f"q = {sp.sstr(q)}")
    print(f"q/(1/6) = {sp.sstr(q / sm_unit)}")
    print(f"q is on SM 1/6 hypercharge lattice: {(q / sm_unit).is_integer}")
    print(f"q/(1/3) = {sp.sstr(q / quark_electric_unit)}")
    print(f"q is on ordinary third-integer electric lattice: {(q / quark_electric_unit).is_integer}")
    print(f"q is integer charged: {(q / color_singlet_integer_unit).is_integer}")
    print()

    print("SU(2)_L multiplets with Y=3/8")
    print("-----------------------------")
    for two_j in range(0, 7):
        j = sp.Rational(two_j, 2)
        charges = su2_component_charges(j, q)
        third_lattice = all((charge / quark_electric_unit).is_integer for charge in charges)
        integer_lattice = all(charge.is_integer for charge in charges)
        print(
            f"j={sp.sstr(j):>3}: Q={','.join(sp.sstr(c) for c in charges):>28} "
            f"third-lattice={third_lattice} integer={integer_lattice}"
        )
    print()

    print("SU(5) comment")
    print("-------------")
    print("Minimal SU(5) hypercharges are generated by entries -1/3 and +1/2,")
    print("so they lie on a 1/6 lattice in the usual SM normalization.")
    print("Because (3/8)/(1/6)=9/4 is not an integer, Y=3/8 is not on that")
    print("ordinary SU(5)/SM charge lattice.")
    print()

    print("Conclusion")
    print("----------")
    print(
        "The paired D-term model is anomaly-safe for scalars or vectorlike "
        "matter, but Y=3/8 is not a standard SM/SU(5)-quantized charge.  "
        "A model using it needs an exotic charge sector or a hidden mechanism."
    )


if __name__ == "__main__":
    main()
