"""Phase D: partial-compositeness sketch -- can a UV completion give the
Casimir-locked seed structure with a = b?

Phase A established: the model's accuracy needs a = b in the seed
matrix to ~10^-3. Phase A also noted: 'the off-diagonal sqrt(C2) and
the diagonal -C2 carry the same prefactor' is the empirical content
of the Casimir lock. This script asks: what UV physics produces this?

It is amusing that, after dismissing the chat's spin-3/2 reading
(internal SU(2) labels are not Lorentz spins, no Rarita-Schwinger
fermion in the spectrum), the natural UV mechanism is partial
compositeness -- where the SU(2) representation labels become the
labels of bound states of a hypercolor sector. The bound states
behave like 'atoms' of SU(N)_HC, and their SU(2) representation
content looks structurally like atomic spectroscopy. The labels are
the same group-theory; only the physical referent (Lorentz spin vs.
bound-state SU(2) charge) differs.

UV setup (Caracciolo-Parolini-Serone-style, arXiv:1211.7290):
  * Hypercolor gauge group: SU(N)_HC, strongly coupled at scale Lambda_HC
  * SU(2)_L is gauged AS A SUBGROUP of a global symmetry of the HC sector
  * Composite scalars Chi_R^a are bound states of HC fermions, in the
    irrep R of SU(2)_L, with a = 1, ..., dim(R) the SU(2) index
  * Elementary scalars Psi_R^a couple to the composite sector via a
    bilinear mixing Lagrangian generated by an adjoint-charged spurion
    epsilon^A T^A (where T^A are the SU(2)_L generators, A = 1, 2, 3):

        L_mix = y * epsilon^A * Psi_R^a (T^A_R)_{ab} Chi_R^b + h.c.

  * Composite mass term, generated by HC strong dynamics:
        L_comp = - m_chi^2 |Chi_R|^2

  * Elementary mass term protected by chiral / discrete symmetry:
        L_elem = 0  (the (1,1) zero of the seed)

This script computes the resulting 2x2 mass matrix in the
(elementary, composite) basis and checks whether the Casimir-locked
form a sqrt(C2), -b C2 with a = b emerges naturally.
"""

from __future__ import annotations

import math
import sys

import sympy as sp


def partial_compositeness_seed_matrix(R: int, m_chi_sq, y, eps):
    """Compute the 2x2 mass matrix in (Psi, Chi) basis from a
    partial-compositeness Lagrangian with adjoint-charged mixing.

    The mixing operator y eps^A Psi (T^A) Chi has matrix elements
    M_mix = y |eps| sqrt(<T^A T^A>_R) = y |eps| sqrt(C2(R)).

    The full mass matrix (in the basis (Psi, Chi)) is:
        M^2 = [[ m_psi^2,                M_mix     ],
               [ M_mix,                 m_chi^2    ]]
    With m_psi^2 = 0 (protected) and M_mix = y |eps| sqrt(C2(R)),
    this is:
        M^2 = m_0^2 [[0,                a sqrt(C2(R))],
                     [a sqrt(C2(R)),    -b C2(R)     ]]
    if we identify
        a sqrt(C2(R)) m_0^2 = y |eps| sqrt(C2(R))     ->  a m_0^2 = y |eps|
        b C2(R) m_0^2 = -m_chi^2                       ->  b m_0^2 = -m_chi^2 / C2(R)
    so that a = y |eps| / m_0^2 and b = -m_chi^2 / (m_0^2 C2(R)).

    For a = b we need:
        y |eps| / m_0^2 = -m_chi^2 / (m_0^2 C2(R))
        =>  m_chi^2 = -y |eps| C2(R)
    i.e., the composite mass-squared is proportional to the SAME
    coupling y |eps| that generates the mixing, with prefactor C2(R).
    """
    j = (R - 1) / 2
    C2 = j * (j + 1)
    sqrt_C2 = sp.sqrt(C2)

    # Off-diagonal mixing: y |eps| sqrt(C2(R))
    M_mix = y * eps * sqrt_C2

    # Build the matrix
    M2 = sp.Matrix([[0, M_mix], [M_mix, m_chi_sq]])
    return M2, C2, sqrt_C2


def main() -> int:
    print("=" * 78)
    print("Phase D: partial-compositeness sketch and the a = b lock")
    print("=" * 78)

    print("\n[1] UV setup")
    print("    SU(N)_HC strong sector, Lambda_HC = TeV-scale")
    print("    SU(2)_L gauged as subgroup of global symmetry G_global of HC")
    print("    Composite scalar Chi_R: bound state of HC fermions, in irrep R of SU(2)_L")
    print("    Elementary scalar Psi_R: SM doublet partner")
    print()
    print("    Mixing Lagrangian: y eps^A Psi (T^A_R) Chi   (adjoint spurion eps^A)")

    print("\n[2] Resulting 2x2 mass matrix in (Psi, Chi) basis")
    y, eps, m_chi_sq = sp.symbols("y eps m_chi^2", positive=True, real=True)

    for R in (2, 3, 4):
        M2, C2, sqrt_C2 = partial_compositeness_seed_matrix(R, -m_chi_sq, y, eps)
        print(f"\n    R = {R}, C_2(R) = {C2}, sqrt(C_2) = {sqrt_C2}")
        print(f"    M^2 = {M2.tolist()}")
        # Eigenvalues
        eigs = M2.eigenvals()
        print(f"    eigenvalues: {[sp.simplify(e) for e in eigs.keys()]}")

    print("\n[3] Normalisation to Casimir-locked seed form")
    print("    The mass matrix in (Psi, Chi) basis is")
    print("        M^2 = [[ 0,                  y|eps|sqrt(C2)  ],")
    print("               [ y|eps|sqrt(C2),    -m_chi^2          ]]")
    print()
    print("    Dividing by some reference scale m_0^2 to compare to our seed:")
    print("        M^2 / m_0^2 = [[0, a sqrt(C2)], [a sqrt(C2), -b C2]]")
    print()
    print("    Identification:")
    print("        a m_0^2 = y |eps|                         (mixing strength)")
    print("        b m_0^2 = m_chi^2 / C2(R)                 (composite mass / C2)")
    print()
    print("    For a = b, partial compositeness REQUIRES")
    print("        m_chi^2 = y |eps| C2(R)")
    print()
    print("    => The composite mass-squared must be proportional to the SAME")
    print("       coupling y|eps| that generates the elementary-composite mixing,")
    print("       with prefactor exactly C2(R).")
    print()
    print("    This is a STRONG constraint on the HC dynamics. It is NOT")
    print("    automatic; it requires that the HC strong-coupling scale and the")
    print("    elementary-composite mixing share a common origin (most plausibly:")
    print("    both are induced by the same higher-dim operator above Lambda_HC).")

    print("\n[4] When does the constraint hold? (qualitative)")
    print("    The relation m_chi^2 = y |eps| C2(R) holds in HC realisations where:")
    print()
    print("    (a) The composite scalar Chi_R receives its mass from the same")
    print("        operator that generates the elementary-composite mixing")
    print("        (e.g., a higher-dim portal Psi^A T^A Chi at Lambda_UV >> Lambda_HC).")
    print()
    print("    (b) The Casimir factor C2(R) reflects the quadratic invariant of")
    print("        the SU(2)_L charge of the bound state, naturally appearing in")
    print("        the mass term as <Chi_R^a T^A_{ab} T^A_{bc} Chi_R^c> = C2(R) <|Chi|^2>.")
    print()
    print("    Both (a) and (b) are STANDARD features of partial-compositeness")
    print("    constructions (cf. Caracciolo-Parolini-Serone, arXiv:1211.7290,")
    print("    Sec. 3-4). They are not unique to our model; they are the generic")
    print("    structure of any composite-scalar sector with adjoint-charged mixing.")

    print("\n[5] Connection to the chat's spin-3/2 dismissal")
    print("    The Casimir labels {1/2, 1, 3/2, ...} of our spectrum tower")
    print("    are the SU(2)_L representation indices of the COMPOSITE BOUND")
    print("    STATES Chi_R, NOT physical Lorentz spins. The bound states are")
    print("    scalars (J=0) carrying internal SU(2)_L charge.")
    print()
    print("    This is structurally analogous to the labels of mesons in QCD:")
    print("    a pion is a (J=0) scalar but carries isospin (SU(2)_isospin)")
    print("    charge I=1 (a triplet); a kaon carries I=1/2 (a doublet); etc.")
    print("    Nobody confuses the isospin label with Lorentz spin.")
    print()
    print("    In our model, the analogue of 'isospin' is the SU(2)_L charge of")
    print("    the HC bound state. The Casimir-locked spectrum is the analogue")
    print("    of an isospin tower of 'mesons' of the hypercolor sector.")
    print()
    print("    This converts the chat's spin-3/2 dismissal into a structural")
    print("    interpretation: the j label is the SU(2)_L charge of a composite")
    print("    scalar bound state. Spin and Casimir share group theory; physical")
    print("    referents differ.")

    print("\n[6] What is missing (Q1, Q2, Q5 of the Status section)")
    print("    Q1: M_W^2 = m_0^2 lambda_+(2) is NOT derived. We have a UV")
    print("        Lagrangian that gives the Casimir-locked seed, but the gauge-")
    print("        boson mass matrix from the doublet VEV (after EWSB) has not")
    print("        been computed in this sketch. Derivation requires the")
    print("        composite-Higgs Coleman-Weinberg potential and minimisation.")
    print()
    print("    Q2: m_h^2 + Delta = ... requires the scalar potential structure")
    print("        AND the spurion mechanism. Both open in this sketch.")
    print()
    print("    Q5: A specific UV completion (choice of N for SU(N)_HC, choice of")
    print("        global symmetry G_global, choice of fermion content) is needed")
    print("        for a quantitative derivation. This is multi-week work; we")
    print("        provide here only the structural identification.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
